Based on the Johnstone notes.

## Universal Algebra

We denote the nullary set $G^0$ as $\{ \emptyset \}$.

[Discussion on singleton set.](https://math.stackexchange.com/questions/921712/what-is-a-set-raised-to-the-0-power-in-relation-to-the-definition-of-a-nullary).

A structure is set equipped with finary operations.

A finary operation is a map from a set $G$ to any of 
$$
G^0, G^1=G, G^2 = G \times G, ...
$$.

::: {#def-OperationalType}
## Operational Type
An operational type is a pair $(\Omega, \alpha)$ with

- set of operation symbols $\Omega$ 
- a map $\alpha : \Omega \mapsto \mathbb{N}$ that assigns each $\omega \in \Omega$ it's arity $\alpha(\omega)$.
:::

::: {#def-OperationalStructure}
## Operational Structure
An operational structure $(\Omega, \alpha)$ is 

- a set $A$ with an operational type $(\Omega, \alpha)$ 

-  a function $\omega_A : A^{\alpha(\omega)} \mapsto A$ for each $\omega \in \Omega$

$\omega_A$ is *the interpretation of abstract symbol* $\omega$ *in the structure $A$*.
:::

::: {#def-Homomorphism}

## Homomorphism 
A map $f:A\mapsto B$ is a homomorphism of $\Omega$ structures $A$ & $B$ if

$$
f(\omega_A (a_1,..., a_n)) = \omega_B (f(a_1),...,f(a_n)) 
$$

where $\alpha(\omega)=n$ and $\forall a_1,...,a_n \in A$
:::

::: {#def-Term}
## The set of $\Omega$-terms in $X$
Let $\Omega$ be an opertaional type and $X$ be a set.

The set $F_{\Omega}(X)$  of $\Omega$ terms is defined inductively:

1. If $x \in X$ then $x \in F_{Ω}(X)$ 
2. If $w \in \Omega$ with $\alpha(w)=n$ and $t_1,...,t_n \in \Omega$ then $wt_1...t_n \in F_{Ω}(X)$.
:::

Note that this really the intersection of all operation structures that contain $X$. 

:::{#thm-FX_is_sigma}
## $F_\Omega(X)$ is a sigma structure
1. The set of $\Omega$-terms in $X$, $F_{\Omega}(X)$ has a \Omega structure.
2. Given any $\Omega$ structure $F_\Omega(X)$ and any map $f:X \mapsto A$ there exists a unique homomorphism $\hat{f}:F_\Omega(X) \mapsto A$

In other words $F_\Omega(X)$ is the free structure generated by $X$
:::
:::{.proof}
## Proof of @thm-FX_is_sigma 
Need to define the interpretation of $\omega$ on FX via 
$$
\omega_{FX}(t_1,...,t_n) = \omega t_1 ... t_n
$$
:::

:::{#lem-XfromFinite}
## X terms from finite
$F_{\Omega}(X)=\bigcup \lbrace F_{\Omega}(X^\prime) \mid X^\prime \subset X \text{ is finite} \rbrace$
:::

:::{#def-derived_operation}
## Derived Operations


Let $X_n= \lbrace x_1,...,x_n \rbrace$, $t \in F_{\Omega}(X_n)$, $A$ be a $\Omega$ structure.

The n-ary derived operation corresponding to $t$, $t_A : A^n \rightarrow A$ is defined as

$\forall \underline{a} \in A^n$

$$
t_A(\underline{a})
= \begin{cases}
    a_i &\text{if } t = x_i \in X_n \\
    \omega_A \lparen t_1(\underline{a}) ,..., t_m(\underline{a}) \rparen
    &\text{if } t = \omega t_1 ... t_m, \text{ for } t_1,...,t_m \in F_{\Omega}(X_n), \alpha(\omega)=m 
\end{cases}
$$
:::

Note this really does just mean we keep applying the standard operations until we get to the X terms.

Therefore a derived operation really is just the map it represents

$t=mx_1 m x_2 x_3$ has interpretation $t_A : \underline{a} \mapsto m a_1 m a_2 a_3$

:::{#def-nary_equation}
## n-ary Equation
An n-ary equation in operational type $(\Omega, \alpha)$ is an expression $(s=t)$ for $s,t \in F_{\Omega}(X_n)$
:::

:::{#def-nary-satisfied}
## Satisfied
An n-ary equation is satisfied in operational structure A iff $t_A \equiv s_A$
:::

:::{#def-algebraic_theory}
## Algebraic Theory
An Algebraic Theory $T=(\Omega, E)$ is an operational type $(\Omega, \alpha)$ and set $E$ of equations in $\Omega$
:::

:::{#def-model}
## Model
A model for an Algebraic Theory $T=(\Omega, E)$ or T-algebra is an Operational Structure $\Omega$ where all equations in $E$ are satisfied.
:::

:::{#def-derived_equations}
## Derived Equations
Let $E$ be a set of equations. The set $\tilde{E}$ of derived equation satisfies:

a. $E \subset \tilde{E}$

a.  $\tilde{E}$ defines an equivalence relation $s \sim_E t \iff (s=t) \in \tilde{E}$ on the set of terms $F_{\Omega}(X)$

    i)
reflexive: $(t=t) \in \tilde{E} \ \forall t \in F_{\Omega}(X)$

    i) 
symetric: $(s=t) \implies (t=s)$

    i) 
transitive: $(s=t),(t=u) \implies (s=u)$

a. Let $s[u / x_i]$ denote replacing symbol $x_i$ with $u$.
  
    i) 
$(s=t) \in \tilde{E} \implies (s[u / x_i] = t[u / x_i])$

    i) 
$(s=t), u \in F_{\Omega}(X_n) \implies u[s/x_i] = u[t/x_i]$

:::

This is just the smallest subset of all possible equations $(s=t)$ such that it is closed under a,b,c.

Group Theory Example

i)
$t = m e x_1 = x_1 = s \in \tilde{E} \implies m e u = u \forall u \in F_{\Omega}(X)$

i)
$u = m x_1 x_2$, $t=s$ as before, $\implies m x_1 \textcolor{red}{mex_1} = m x_1 \textcolor{red}{x_1}$
